language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
  - cassandra
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script: travis_wait 45 ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V